import { precacheAndRoute } from 'workbox-precaching';

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen for the install event
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

// Listen for the activate event
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
